version: 2.1
jobs:
  build:
    parallelism: 2
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run:
          name: Run Ktlint
          command: ./gradlew ktlint
      - run:
          name: Run Lint
          command: ./gradlew lintDebug
      - run:
          name: Run Test
          command: ./gradlew clean test
      - run:
          name: "Save coverage to codecov"
          command: |
            bash <(curl -s https://codecov.io/bash)
      - run:
          name: Assemble project
          command: ./gradlew assemble